// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// convert2posX
NumericVector convert2posX(NumericVector chr, NumericVector bp, NumericVector posX);
RcppExport SEXP ggman_convert2posX(SEXP chrSEXP, SEXP bpSEXP, SEXP posXSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bp(bpSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type posX(posXSEXP);
    __result = Rcpp::wrap(convert2posX(chr, bp, posX));
    return __result;
END_RCPP
}
// split_markername
NumericMatrix split_markername(std::vector<std::string> markers, int n, char sep);
RcppExport SEXP ggman_split_markername(SEXP markersSEXP, SEXP nSEXP, SEXP sepSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type markers(markersSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< char >::type sep(sepSEXP);
    __result = Rcpp::wrap(split_markername(markers, n, sep));
    return __result;
END_RCPP
}
