# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

..convert2posX <- function(chr, bp, posX) {
    .Call('ggman_convert2posX', PACKAGE = 'ggman', chr, bp, posX)
}

#' @export
split_markername <- function(markers, n = 2L, sep = ':', replaceXYMT = FALSE) {
    .Call('ggman_split_markername', PACKAGE = 'ggman', markers, n, sep, replaceXYMT)
}

